### ISSUE TITLE
clBuildProgram crash in the inliner

### ISSUE THREAD

**Issue by pjaaskel** [intel/compute-runtime#283]
When building [Glow](https://github.com/pytorch/glow) neural networks with the OpenCL GPU driver, there's a crash at LLVM inliner (?).  It used to still work at least with pytorch/glow@4956b05c2d7e43b441427abfd7962df8fb444484.

It still works with the Intel's CPU driver and pocl.

Reproduction is simple. For example:

```
OCL_ICD_VENDORS=/etc/OpenCL/vendors/intel.icd ./bin/image-classifier -backend=OpenCL ../../glow/build-unity/tests/images/imagenet/cat_285.png -expected-labels=281 -image-mode=0to255 -m ../../glow/build-unity/inception_v1/model.onnx -model-input-name=data_0
```

Backtrace:

```
#0  0x00007fffe5879316 in llvm::ValueHandleBase::AddToUseList() () from /usr/local/lib/libigc.so.1
#1  0x00007fffe536389f in ?? () from /usr/local/lib/libigc.so.1
#2  0x00007fffe5378fb1 in llvm::InlineFunction(llvm::CallSite, llvm::InlineFunctionInfo&, llvm::AAResults*, bool, llvm::Function*) () from /usr/local/lib/libigc.so.1
#3  0x00007fffe50f18a7 in llvm::LegacyInlinerBase::inlineCalls(llvm::CallGraphSCC&) () from /usr/local/lib/libigc.so.1
#4  0x00007fffe54a1f26 in ?? () from /usr/local/lib/libigc.so.1
#5  0x00007fffe582931c in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/local/lib/libigc.so.1
#6  0x00007fffe4c45b58 in ?? () from /usr/local/lib/libigc.so.1
#7  0x00007fffe4adedc0 in ?? () from /usr/local/lib/libigc.so.1
#8  0x00007fffe4ba9e62 in ?? () from /usr/local/lib/libigc.so.1
#9  0x00007fffef3889be in ?? () from /usr/local/lib/intel-opencl/libigdrcl.so
#10 0x00007fffef1cbffa in ?? () from /usr/local/lib/intel-opencl/libigdrcl.so
#11 0x00007fffef16ef98 in ?? () from /usr/local/lib/intel-opencl/libigdrcl.so
#12 0x0000555557d66ed1 in glow::OpenCLFunction::createProgram (this=this@entry=0x7fffde30f580, 
    source="/**\n * Copyright (c) Glow Contributors. See CONTRIBUTORS file.\n *\n * Licensed under the Apache License, Version 2.0 (the \"License\");\n * you may not use this file except in compliance with the License."..., options=std::vector of length 1, capacity 1 = {...}, queue=queue@entry=0x7fffdfc0e150)
    at ../lib/Backends/OpenCL/OpenCL.cpp:347
....
```

I believe it's trying to build this kernel program:

https://github.com/pytorch/glow/blob/master/lib/Backends/OpenCL/kernels.cl

I tried upgrading my Intel(R) Graphics Compute Runtime to 20.11.16158, it didn't help.

**Comment by JacekDanecki** [comment]
I've moved this issue to IGC: https://github.com/intel/intel-graphics-compiler/issues/127, as crash is in compiler. Closing issue here.
