### ISSUE TITLE
Ubuntu 18.04 with intel-opencl-icd 21.19.19792-1~ppa1~bionic1: SIGFPE

### ISSUE THREAD

**Issue by koitsu** [intel/compute-runtime#424]
Since updating `intel-opencl-icd` to `21.19.19792-1~ppa1~bionic1`, I've begun to see 100% reproducible SIGFPE on all IGD-related programs (clinfo, dnetc, etc.).  This is on an Intel NUC5i5RYK.  Focusing on `clinfo` just to make my life easier.

```
(00:42:59 jdc@linux2) ~/dnetc521-linux-amd64-opencl $ dpkg -l intel-opencl-icd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                     Version                   Architecture              Description
+++-========================================-=========================-=========================-=====================================================================================
ii  intel-opencl-icd                         21.19.19792-1~ppa1~bionic amd64                     Intel graphics compute runtime for OpenCL
```

Some examples:

```
(00:40:38 jdc@linux2) ~/dnetc521-linux-amd64-opencl $ strace clinfo
...
munmap(0x7f7e87dde000, 31530)           = 0
getdents(3, /* 0 entries */, 32768)     = 0
unlink("igdrcl.log")                    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/dri/by-path", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 4
fstat(4, {st_mode=S_IFDIR|0755, st_size=80, ...}) = 0
getdents(4, /* 4 entries */, 32768)     = 144
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
openat(AT_FDCWD, "/dev/dri/by-path/pci-0000:00:02.0-render", O_RDWR) = 4
ioctl(4, DRM_IOCTL_VERSION, 0x7ffc1aa05110) = 0
ioctl(4, DRM_IOCTL_I915_GETPARAM or DRM_IOCTL_TEGRA_CLOSE_CHANNEL, 0x7ffc1aa051f0) = 0
ioctl(4, DRM_IOCTL_I915_GETPARAM or DRM_IOCTL_TEGRA_CLOSE_CHANNEL, 0x7ffc1aa051f0) = 0
ioctl(4, _IOC(_IOC_READ|_IOC_WRITE, 0x64, 0x79, 0x10), 0x7ffc1aa05100) = -1 EINVAL (Invalid argument)
ioctl(4, DRM_IOCTL_I915_GETPARAM or DRM_IOCTL_TEGRA_CLOSE_CHANNEL, 0x7ffc1aa05180) = 0
ioctl(4, DRM_IOCTL_I915_GETPARAM or DRM_IOCTL_TEGRA_CLOSE_CHANNEL, 0x7ffc1aa05180) = 0
--- SIGFPE {si_signo=SIGFPE, si_code=FPE_INTDIV, si_addr=0x7f7e86f5416f} ---
+++ killed by SIGFPE +++
Floating point exception
```
Kernel outputs the following for this crash:
```
[  595.485667] traps: clinfo[1473] trap divide error ip:7ff83c11916f sp:7ffcad4dd950 error:0 in libigdrcl.so[7ff83bd69000+47e000]
```
Running normally (i.e. not within strace) but with `LD_DEBUG=libs` shows the crash is in Intel's own library:

```
(00:42:08 jdc@linux2) ~/dnetc521-linux-amd64-opencl $ LD_DEBUG=libs clinfo
      1521:     find library=libOpenCL.so.1 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/usr/lib/x86_64-linux-gnu/libOpenCL.so.1
      1521:
      1521:     find library=libdl.so.2 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/lib/x86_64-linux-gnu/libdl.so.2
      1521:
      1521:     find library=libc.so.6 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/lib/x86_64-linux-gnu/libc.so.6
      1521:
      1521:
      1521:     calling init: /lib/x86_64-linux-gnu/libc.so.6
      1521:
      1521:
      1521:     calling init: /lib/x86_64-linux-gnu/libdl.so.2
      1521:
      1521:
      1521:     calling init: /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
      1521:
      1521:
      1521:     initialize program: clinfo
      1521:
      1521:
      1521:     transferring control: clinfo
      1521:
      1521:     find library=libpthread.so.0 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/lib/x86_64-linux-gnu/libpthread.so.0
      1521:
      1521:     find library=libigdgmm.so.11 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/usr/lib/x86_64-linux-gnu/libigdgmm.so.11
      1521:
      1521:     find library=libstdc++.so.6 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
      1521:
      1521:     find library=libm.so.6 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/lib/x86_64-linux-gnu/libm.so.6
      1521:
      1521:     find library=libgcc_s.so.1 [0]; searching
      1521:      search cache=/etc/ld.so.cache
      1521:       trying file=/lib/x86_64-linux-gnu/libgcc_s.so.1
      1521:
      1521:
      1521:     calling init: /lib/x86_64-linux-gnu/libpthread.so.0
      1521:
      1521:
      1521:     calling init: /lib/x86_64-linux-gnu/libgcc_s.so.1
      1521:
      1521:
      1521:     calling init: /lib/x86_64-linux-gnu/libm.so.6
      1521:
      1521:
      1521:     calling init: /usr/lib/x86_64-linux-gnu/libstdc++.so.6
      1521:
      1521:
      1521:     calling init: /usr/lib/x86_64-linux-gnu/libigdgmm.so.11
      1521:
      1521:
      1521:     calling init: /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
      1521:
Floating point exception
```

Other information per some other issues I read:

```
(00:44:40 jdc@linux2) ~ $ lspci -vnn
00:00.0 Host bridge [0600]: Intel Corporation Broadwell-U Host Bridge -OPI [8086:1604] (rev 09)
        Subsystem: Intel Corporation Broadwell-U Host Bridge -OPI [8086:2057]
        Flags: bus master, fast devsel, latency 0
        Capabilities: <access denied>
        Kernel driver in use: bdw_uncore

00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 6000 [8086:1626] (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation HD Graphics 6000 [8086:2057]
        Flags: bus master, fast devsel, latency 0, IRQ 45
        Memory at a9000000 (64-bit, non-prefetchable) [size=16M]
        Memory at b0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 3000 [size=64]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915

00:03.0 Audio device [0403]: Intel Corporation Broadwell-U Audio Controller [8086:160c] (rev 09)
        Subsystem: Intel Corporation Broadwell-U Audio Controller [8086:2057]
        Flags: bus master, fast devsel, latency 0, IRQ 48
        Memory at aa034000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

00:14.0 USB controller [0c03]: Intel Corporation Wildcat Point-LP USB xHCI Controller [8086:9cb1] (rev 03) (prog-if 30 [XHCI])
        Subsystem: Intel Corporation Wildcat Point-LP USB xHCI Controller [8086:2057]
        Flags: bus master, medium devsel, latency 0, IRQ 42
        Memory at aa020000 (64-bit, non-prefetchable) [size=64K]
        Capabilities: <access denied>
        Kernel driver in use: xhci_hcd

00:16.0 Communication controller [0780]: Intel Corporation Wildcat Point-LP MEI Controller #1 [8086:9cba] (rev 03)
        Subsystem: Intel Corporation Wildcat Point-LP MEI Controller [8086:2057]
        Flags: bus master, fast devsel, latency 0, IRQ 46
        Memory at aa03d000 (64-bit, non-prefetchable) [size=32]
        Capabilities: <access denied>
        Kernel driver in use: mei_me
        Kernel modules: mei_me

00:19.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection (3) I218-V [8086:15a3] (rev 03)
        Subsystem: Intel Corporation Ethernet Connection (3) I218-V [8086:2057]
        Flags: bus master, fast devsel, latency 0, IRQ 44
        Memory at aa000000 (32-bit, non-prefetchable) [size=128K]
        Memory at aa03b000 (32-bit, non-prefetchable) [size=4K]
        I/O ports at 3080 [size=32]
        Capabilities: <access denied>
        Kernel driver in use: e1000e
        Kernel modules: e1000e

00:1b.0 Audio device [0403]: Intel Corporation Wildcat Point-LP High Definition Audio Controller [8086:9ca0] (rev 03)
        Subsystem: Intel Corporation Wildcat Point-LP High Definition Audio Controller [8086:2057]
        Flags: bus master, fast devsel, latency 32, IRQ 47
        Memory at aa030000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

00:1d.0 USB controller [0c03]: Intel Corporation Wildcat Point-LP USB EHCI Controller [8086:9ca6] (rev 03) (prog-if 20 [EHCI])
        Subsystem: Intel Corporation Wildcat Point-LP USB EHCI Controller [8086:2057]
        Flags: bus master, medium devsel, latency 0, IRQ 23
        Memory at aa03a000 (32-bit, non-prefetchable) [size=1K]
        Capabilities: <access denied>
        Kernel driver in use: ehci-pci

00:1f.0 ISA bridge [0601]: Intel Corporation Wildcat Point-LP LPC Controller [8086:9cc3] (rev 03)
        Subsystem: Intel Corporation Wildcat Point-LP LPC Controller [8086:2057]
        Flags: bus master, medium devsel, latency 0
        Capabilities: <access denied>
        Kernel driver in use: lpc_ich
        Kernel modules: lpc_ich

00:1f.2 SATA controller [0106]: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] [8086:9c83] (rev 03) (prog-if 01 [AHCI 1.0])
        Subsystem: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] [8086:2057]
        Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 43
        I/O ports at 30d0 [size=8]
        I/O ports at 30c0 [size=4]
        I/O ports at 30b0 [size=8]
        I/O ports at 30a0 [size=4]
        I/O ports at 3060 [size=32]
        Memory at aa039000 (32-bit, non-prefetchable) [size=2K]
        Capabilities: <access denied>
        Kernel driver in use: ahci
        Kernel modules: ahci

00:1f.3 SMBus [0c05]: Intel Corporation Wildcat Point-LP SMBus Controller [8086:9ca2] (rev 03)
        Subsystem: Intel Corporation Wildcat Point-LP SMBus Controller [8086:2057]
        Flags: medium devsel, IRQ 10
        Memory at aa038000 (64-bit, non-prefetchable) [size=256]
        I/O ports at 3040 [size=32]
        Kernel modules: i2c_i801

(00:44:46 jdc@linux2) ~ $ lsmod
Module                  Size  Used by
intel_rapl             20480  0
x86_pkg_temp_thermal    16384  0
intel_powerclamp       16384  0
coretemp               16384  0
kvm_intel             217088  0
kvm                   614400  1 kvm_intel
irqbypass              16384  1 kvm
ir_rc6_decoder         16384  0
intel_cstate           20480  0
snd_hda_codec_realtek   110592  1
snd_hda_codec_hdmi     49152  1
intel_rapl_perf        16384  0
snd_hda_codec_generic    73728  1 snd_hda_codec_realtek
rc_rc6_mce             16384  0
snd_hda_intel          45056  0
ir_lirc_codec          16384  0
lirc_dev               16384  2 ir_lirc_codec
snd_hda_codec         126976  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
nuvoton_cir            20480  0
snd_hda_core           81920  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
rc_core                36864  6 lirc_dev,ir_lirc_codec,ir_rc6_decoder,rc_rc6_mce,nuvoton_cir
snd_hwdep              20480  1 snd_hda_codec
mei_me                 40960  0
snd_pcm                98304  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
mei                    94208  1 mei_me
mac_hid                16384  0
snd_timer              32768  1 snd_pcm
snd                    81920  8 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_pcm
soundcore              16384  1 snd
lpc_ich                24576  0
acpi_pad              180224  0
sch_fq_codel           20480  2
ib_iser                49152  0
rdma_cm                61440  1 ib_iser
iw_cm                  45056  1 rdma_cm
ib_cm                  53248  1 rdma_cm
ib_core               225280  4 rdma_cm,iw_cm,ib_iser,ib_cm
iscsi_tcp              20480  0
libiscsi_tcp           20480  1 iscsi_tcp
libiscsi               53248  3 libiscsi_tcp,iscsi_tcp,ib_iser
scsi_transport_iscsi    98304  3 iscsi_tcp,ib_iser,libiscsi
ip_tables              28672  0
x_tables               40960  1 ip_tables
autofs4                40960  2
btrfs                1155072  0
zstd_compress         163840  1 btrfs
raid10                 53248  0
raid456               147456  0
async_raid6_recov      20480  1 raid456
async_memcpy           16384  2 raid456,async_raid6_recov
async_pq               16384  2 raid456,async_raid6_recov
async_xor              16384  3 async_pq,raid456,async_raid6_recov
async_tx               16384  5 async_pq,async_memcpy,async_xor,raid456,async_raid6_recov
xor                    24576  2 async_xor,btrfs
raid6_pq              114688  4 async_pq,btrfs,raid456,async_raid6_recov
libcrc32c              16384  1 raid456
raid1                  40960  0
raid0                  20480  0
multipath              16384  0
linear                 16384  0
i915                 1622016  1
i2c_algo_bit           16384  1 i915
drm_kms_helper        172032  1 i915
syscopyarea            16384  1 drm_kms_helper
crct10dif_pclmul       16384  0
crc32_pclmul           16384  0
sysfillrect            16384  1 drm_kms_helper
ghash_clmulni_intel    16384  0
e1000e                249856  0
pcbc                   16384  0
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
aesni_intel           188416  0
ptp                    20480  1 e1000e
aes_x86_64             20480  1 aesni_intel
crypto_simd            16384  1 aesni_intel
ahci                   40960  1
glue_helper            16384  1 aesni_intel
cryptd                 24576  3 crypto_simd,ghash_clmulni_intel,aesni_intel
drm                   401408  3 drm_kms_helper,i915
libahci                32768  1 ahci
pps_core               20480  1 ptp
video                  45056  1 i915
(00:44:47 jdc@linux2) ~ $ dmesg | egrep -i 'i915|drm'
[    4.362225] [drm] Memory usable by graphics device = 4096M
[    4.372297] ata4.00: supports DRM functions and may not be fully accessible
[    4.374052] ata4.00: supports DRM functions and may not be fully accessible
[    4.780920] fb: switching to inteldrmfb from VESA VGA
[    4.803248] [drm] Replacing VGA console driver
[    4.809498] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    4.809504] [drm] Driver supports precise vblank timestamp query.
[    4.811654] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    4.814291] [drm] Initialized i915 1.6.0 20171023 for 0000:00:02.0 on minor 0
[    4.846113] [drm] Cannot find any crtc or sizes
[    4.862106] [drm] Cannot find any crtc or sizes
[    7.494247] snd_hda_intel 0000:00:03.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
(00:44:56 jdc@linux2) ~ $ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-4.15.0-143-generic root=UUID=e60ab782-7324-4fb4-bab3-81f216ceb7fe ro maybe-ubiquity ipv6.disable=1
(00:44:59 jdc@linux2) ~ $ ls -lR /dev/dri
/dev/dri:
total 0
drwxr-xr-x 2 root root        80 May 24 00:28 by-path
crw-rw---- 1 root video 226,   0 May 24 00:28 card0
crw-rw---- 1 root video 226, 128 May 24 00:28 renderD128

/dev/dri/by-path:
total 0
lrwxrwxrwx 1 root root  8 May 24 00:28 pci-0000:00:02.0-card -> ../card0
lrwxrwxrwx 1 root root 13 May 24 00:28 pci-0000:00:02.0-render -> ../renderD128
(00:45:02 jdc@linux2) ~ $ groups
jdc adm cdrom sudo dip video plugdev lxd docker
```

Please advise.

**Comment by koitsu** [comment]
Kind of smells like https://github.com/intel/compute-runtime/issues/421 but isn't; manifests substantially differently.  I'm left wondering if someone broke some ABI semantics between libOpenCL.so and libigdrcl.so (suspecting the latter, since libOpenCL.so hasn't changed in 4 years):

```
(01:04:55 jdc@linux2) ~ $ gdb /usr/bin/clinfo
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/clinfo...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/clinfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGFPE, Arithmetic exception.
0x00007ffff716a16f in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
(gdb) f 0
#0  0x00007ffff716a16f in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
(gdb) disass
No function contains program counter for selected frame.
(gdb) bt full
#0  0x00007ffff716a16f in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
No symbol table info available.
#1  0x00007ffff6e1681d in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
No symbol table info available.
#2  0x00007ffff716e510 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
No symbol table info available.
#3  0x00007ffff7114de1 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
No symbol table info available.
#4  0x00007ffff7115683 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
No symbol table info available.
#5  0x00007ffff6e0e2a7 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
No symbol table info available.
#6  0x00007ffff7bcca66 in ?? () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
No symbol table info available.
#7  0x00007ffff7bcd0d3 in clGetPlatformIDs () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
No symbol table info available.
#8  0x000055555555a722 in ?? ()
No symbol table info available.
#9  0x00007ffff75f4bf7 in __libc_start_main (main=0x55555555a5d0, argc=1, argv=0x7fffffffe4d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe4c8) at ../csu/libc-start.c:310
        self = <optimized out>
        __self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -4470602088582343427, 93824992258832, 140737488348368, 0, 0, -7737062915239439107, -7737044503943441155}, mask_was_saved = 0}},
          priv = {pad = {0x0, 0x0, 0x7ffff7de38d3 <_dl_init+259>, 0x7ffff7dd14b0}, data = {prev = 0x0, cleanup = 0x0, canceltype = -136431405}}}
        not_first_call = <optimized out>
#10 0x000055555555ab3a in ?? ()
No symbol table info available.
```

**Comment by JacekDanecki** [comment]
Release 21.19.19792 introduced regression on Ubuntu 18.04 with default kernel, see release notes: https://github.com/intel/compute-runtime/releases/tag/21.19.19792
You can update your kernel to linux-image-generic-hwe-18.04 or recompile Neo with fix from commit: https://github.com/intel/compute-runtime/commit/21d93a33d20810dcfc3fbc70bee6aae7a4e57ecc

**Comment by koitsu** [comment]
Great, glad to know I wasn't losing my mind and that this was a regression!  :)  I've gone ahead and updated the Ubuntu 18.04 kernel [per Canonical's instructions](https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Ubuntu_18.04_LTS_-_Bionic_Beaver) or more precisely, this:

```
sudo apt-get install --install-recommends linux-generic-hwe-18.04
sudo apt-get autoremove
sudo reboot
```
Now all OpenCL applications are functional.  Thank you very much!
